// Auth
export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'

// myStore
export const POST_PRODUCT = 'POST_PRODUCT'
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'
export const SET_IMAGE_PRODUCT = 'SET_IMAGE_PRODUCT'
export const SET_NAME_PRODUCT = 'SET_NAME_PRODUCT'
export const SET_DES_PRODUCT = 'SET_DES_PRODUCT'
export const SET_CATEGORY_PRODUCT = 'SET_CATEGORY_PRODUCT'
export const SET_VALUE_CLASSIFY_PRODUCT = 'SET_VALUE_CLASSIFY_PRODUCT'
export const REMOVE_VALUE_CLASSIFY_PRODUCT = 'REMOVE_VALUE_CLASSIFY_PRODUCT'
export const SET_VALUE_PRICE = 'SET_VALUE_PRICE'
export const SET_VALUE_QUANTITY = 'SET_VALUE_QUANTITY'
export const SET_VALUE_TRANSPORTFEE = 'SET_VALUE_TRANSPORTFEE'
export const POST_SUCCESS = 'POST_SUCCESS'
export const POST_FAILD = 'POST_FAILD'

// Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'