// Auth
export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'

// myStore
export const POST_PRODUCT = 'POST_PRODUCT'
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'
export const SET_NAME_PRODUCT = 'SET_NAME_PRODUCT'
export const SET_DES_PRODUCT = 'SET_DES_PRODUCT'
export const SET_CATEGORY_PRODUCT = 'SET_CATEGORY_PRODUCT'
export const SET_VALUE_CLASSIFY_PRODUCT = 'SET_VALUE_CLASSIFY_PRODUCT'
export const REMOVE_VALUE_CLASSIFY_PRODUCT = 'REMOVE_VALUE_CLASSIFY_PRODUCT'
export const ADD_VALUE_CLASSIFY0_PRODUCT = 'ADD_VALUE_CLASSIFY0_PRODUCT'
export const ADD_VALUE_CLASSIFY1_PRODUCT = 'ADD_VALUE_CLASSIFY1_PRODUCT'
